name: mypage

on:
  push:
    branches: [flutter]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          # baseHref: /insung3511.github.io/
          workingDir: ./mypage/web